### ISSUE TITLE
Feature request: Change FileResource.Data in custom FileResource impl

### ISSUE THREAD

**Issue by NotNite** [NotAdam/Lumina#63]
FileResource.Data has an internal setter, so you can't change it in your own FileResource implementations. This will lead to a potential footgun when using [Xande](https://github.com/xivdev/Xande) - there is a method to change the data inside of a .sklb file, but it can't update Data, so I had to write my own `Write` method to write it to a stream.

**Comment by lmcintyre** [comment]
Writing to data is not supported or planned at this moment.

**Comment by NotAdam** [comment]
it wasn't ever not planned, but it's certainly not supported as is - i could never really decide on a decent way of structuring reading & writing in a sane way, because invariably you end up (as is, anyway) with things that work one way when reading a file but don't really make sense when writing a file

generally speaking though, `FileResource` types are only meant for reading files, and you would use some sort of builder or otherwise to build and write a stream which can then be read back with `FileResource`. there could be a scenario where it makes sense for `FileResource`s to be writable, but that would be pretty shit as is just because of the way they're written

**Comment by NotAdam** [comment]
as an aside to the above, it makes sense for file writing to exist in lumina, given a lot of collateral for reading already exists, but I don't think I'd accept something that isn't separate as that would likely make what's there more complicated/annoying to use - but open to suggestions all the same if someone thinks they have a good idea on how that could work
